from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')
m=re.search(r'<script id="payload" type="text/plain">(.*?)</script>',s,re.S)
if not m:
    raise SystemExit('embedded payload not found')
payload=m.group(1).strip()

html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>서울특별시교육청 계약업무 지침 챗봇</title><style>
:root{--bg:#f5f7fb;--card:#fff;--line:#e4e7ec;--ink:#172033;--muted:#667085;--brand:#3157d5;--good:#067647}*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,"Noto Sans KR",sans-serif;background:var(--bg);color:var(--ink)}.wrap{max-width:1080px;margin:auto;padding:28px 18px 56px}.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.title h1{font-size:27px;margin:0 0 6px}.title p{margin:0;color:var(--muted)}.badge{font-size:12px;padding:7px 10px;border-radius:999px;background:#ecfdf3;color:var(--good);white-space:nowrap}.panel{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 10px 26px #10182810}.chips{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 14px}.chip{border:1px solid #cfd4dc;background:#fff;color:#344054;border-radius:999px;padding:7px 11px;font-size:13px;cursor:pointer}.chip:hover{border-color:var(--brand);color:var(--brand)}textarea{width:100%;min-height:92px;resize:vertical;border:1px solid #d0d5dd;border-radius:13px;padding:13px 14px;font:inherit;outline:none}textarea:focus{border-color:var(--brand);box-shadow:0 0 0 3px #3157d51a}.actions{display:flex;gap:8px;align-items:center;margin-top:10px}.go{border:0;border-radius:11px;background:var(--brand);color:#fff;padding:10px 17px;font-weight:800;cursor:pointer}.hint{font-size:12px;color:var(--muted)}#result{margin-top:18px}.answer{border:1px solid #c7d2fe;background:#f8faff;border-radius:16px;padding:16px}.answer h2{font-size:17px;margin:0 0 9px}.answerText{line-height:1.75;font-size:15px}.refs{margin-top:14px;display:grid;gap:10px}.ref{background:#fff;border:1px solid var(--line);border-radius:13px;padding:13px}.loc{font-size:12px;font-weight:800;color:var(--brand);margin-bottom:6px}.snippet{line-height:1.65;white-space:pre-wrap}.score{font-size:11px;color:var(--muted);margin-top:7px}.empty{padding:16px;border:1px dashed #cfd4dc;border-radius:13px;color:var(--muted)}mark{background:#fff0a6;padding:0 1px;border-radius:3px}.warn{margin-top:12px;font-size:12px;color:#7a2e0e;background:#fff7ed;border:1px solid #fed7aa;padding:9px 11px;border-radius:10px}@media(max-width:700px){.head{display:block}.badge{display:inline-block;margin-top:10px}.title h1{font-size:23px}}
</style></head><body><div class="wrap"><div class="head"><div class="title"><h1>계약업무 처리지침 챗봇</h1><p>서울특별시교육청 2023.12.27. 개정 지침 · JSON 완전 내장형</p></div><div class="badge" id="status">문서 불러오는 중</div></div><div class="panel"><div class="chips" id="chips"></div><textarea id="q" placeholder="예: 1인 수의계약 얼마까지 가능해?\n예: 물품 계약할 때 필요한 서류 알려줘"></textarea><div class="actions"><button class="go" id="go">질문하기</button><span class="hint">Enter로 질문 · Shift+Enter 줄바꿈</span></div><div id="result"></div></div></div><script id="payload" type="text/plain">__PAYLOAD__</script><script>
const SYN={'수의계약':['수의 계약','1인견적','1인 견적','2인이상 견적','견적제출','수의견적'],'1인수의':['1인견적','1인 견적','1인 수의','1인수의','단독계약'],'2인견적':['2인이상','2인 이상','2인이상 견적','견적제출'],'계약서':['계약서','승낙사항','계약 체결','계약체결'],'서류':['구비서류','제출서류','징구','서류명','확인서','증명서','계약서류'],'생략':['생략','면제','해당없음','작성 생략','제출 생략'],'가능':['가능','할 수 있다','의할 수 있다','권장','허용'],'금액':['금액','추정가격','계약금액','품의금액','구매총액','예정가격'],'물품':['물품','구매','제조·구매','제조 구매'],'용역':['용역','과업','착수','완료'],'공사':['공사','착공','준공','시공'],'안전':['안전','보건','산업안전','추락','위험성평가','보호구'],'위원회':['위원회','통합선정위원회','평가위원회','선정위원회'],'우선구매':['우선구매','공공구매','여성기업','장애인기업','중소기업','사회적경제기업','녹색제품'],'반복':['반복적','동일업체','회계연도','4회'],'전자계약':['전자계약','지정정보처리장치','전자시담','G2B','S2B']};
const STOP=['알려줘','알려주세요','궁금해','어떻게','뭐야','무엇','어떤','인가요','인가','되나요','돼','되나','가능해','가능한가','해야해','해야','해줘','좀','관련','기준','경우','대한','있어','있나요','그리고','또','그럼'];
function numNorm(s){s=String(s||'').replace(/,/g,'');s=s.replace(/(\\d+)\\s*억원/g,(_,n)=>String(+n*100000000));s=s.replace(/(\\d+)\\s*천\\s*만원/g,(_,n)=>String(+n*10000000));s=s.replace(/(\\d+)\\s*천만원/g,(_,n)=>String(+n*10000000));s=s.replace(/(\\d+)\\s*백\\s*만원/g,(_,n)=>String(+n*1000000));s=s.replace(/(\\d+)\\s*백만원/g,(_,n)=>String(+n*1000000));s=s.replace(/(\\d+)\\s*십\\s*만원/g,(_,n)=>String(+n*100000));s=s.replace(/(\\d+)\\s*만원/g,(_,n)=>String(+n*10000));return s}
function norm(s){return numNorm(String(s||'').toLowerCase()).replace(/[^0-9a-z가-힣%]+/g,' ').replace(/\\s+/g,' ').trim()}
function stems(s){return norm(s).split(' ').filter(Boolean).map(w=>w.replace(/(으로|에서|에게|까지|부터|이면|라면|하는|하고|하면|해야|되나요|됩니까|인가요|인가|은|는|이|가|을|를|에|의|도|만|과|와|로|좀)$/,'')).filter(w=>w.length>1)}
function expand(q){let a=[...stems(q)],nq=norm(q);for(const[k,vs]of Object.entries(SYN)){if(nq.includes(norm(k))||vs.some(v=>nq.includes(norm(v)))){a.push(norm(k));vs.forEach(v=>a.push(norm(v)))}}return[...new Set(a.filter(x=>x&&!STOP.includes(x)))]}
function splitContent(arr){const out=[];(arr||[]).forEach((x,i)=>{const t=String(x||'').trim();if(!t)return;const ps=t.split(/(?<=[.!?。])\\s+|(?=\\d+\\)\\s)|(?=\\b[가-하]\\.\\s)/g).map(x=>x.trim()).filter(Boolean);(ps.length?ps:[t]).forEach((p,j)=>out.push({text:p,ord:i*10+j}))});return out}
async function decode(){const b=Uint8Array.from(atob(document.getElementById('payload').textContent.trim()),c=>c.charCodeAt(0));const ds=new DecompressionStream('gzip');return JSON.parse(await new Response(new Blob([b]).stream().pipeThrough(ds)).text())}
let DB,IDX=[];function build(db){const a=[];(db.chapters||[]).forEach(ch=>(ch.sections||[]).forEach(s=>{const loc=`제${ch.number}장 ${ch.title} > 제${s.number}절 ${s.title}`;splitContent(s.content).forEach(z=>a.push({type:'본문',loc,text:z.text,ord:z.ord}))}));(db.appendices||[]).forEach(x=>{const loc=`붙임 ${x.id} ${x.title}`;splitContent(x.content).forEach(z=>a.push({type:'붙임',loc,text:z.text,ord:z.ord}))});return a}
function scoreItem(it,q,terms){const t=norm(it.loc+' '+it.text);let s=0,nq=norm(q);terms.forEach(term=>{if(t.includes(term))s+=term.length>=4?5:3;term.split(' ').forEach(p=>{if(p.length>1&&t.includes(p))s+=1})});if(nq&&t.includes(nq))s+=18;(numNorm(q).match(/\\d{5,}/g)||[]).forEach(n=>{if(t.includes(n))s+=12});if(/얼마|금액|몇 ?만원|한도/.test(q)&&/(추정가격|계약금액|구매총액|만원|억원|금액)/.test(it.text))s+=8;if(/서류|준비|제출|징구|필요/.test(q)&&/(서류|징구|제출|확인서|증명서|계약서|신고서|서약서)/.test(it.text))s+=7;if(/생략|안 ?써|없어도|면제/.test(q)&&/(생략|면제|해당없음|대체)/.test(it.text))s+=10;if(/안전|보건|추락|위험/.test(q)&&/(안전|보건|추락|위험|보호구)/.test(it.text))s+=8;return s}
function retrieve(q){const terms=expand(q),sc=IDX.map(it=>({...it,score:scoreItem(it,q,terms)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score),p=[];for(const x of sc){if(p.length>=12)break;if(!p.some(y=>y.loc===x.loc&&Math.abs(y.ord-x.ord)<2))p.push(x)}return p}
function nearby(h){const same=IDX.filter(x=>x.loc===h.loc).sort((a,b)=>a.ord-b.ord),k=same.findIndex(x=>x.ord===h.ord&&x.text===h.text);return same.slice(Math.max(0,k-1),Math.min(same.length,k+3))}
function intent(q){if(/서류|준비|제출|징구|구비/.test(q))return'docs';if(/얼마|금액|한도|몇 ?만원|몇 ?억/.test(q))return'amount';if(/생략|안 ?써|없어도|면제/.test(q))return'omit';if(/안전|보건|추락|위험/.test(q))return'safety';if(/몇 ?명|구성|위원/.test(q))return'committee';return'general'}
function best(q,hits){const c=[];hits.slice(0,7).forEach(h=>nearby(h).forEach(x=>c.push({...x,score:scoreItem(x,q,expand(q))})));const seen=new Set(),o=[];for(const x of c.sort((a,b)=>b.score-a.score)){const k=norm(x.text);if(k.length<4||seen.has(k))continue;seen.add(k);o.push(x);if(o.length>=6)break}return o}
function synth(q,hits){if(!hits.length)return{text:'첨부 지침에서 질문과 관련된 내용을 찾지 못했습니다. 질문을 조금 더 구체적으로 입력해 주세요.',refs:[]};const it=intent(q),ss=best(q,hits);let c=ss;if(it==='amount')c=ss.filter(x=>/(만원|억원|금액|추정가격|계약금액|구매총액)/.test(x.text)).slice(0,4);else if(it==='docs')c=ss.filter(x=>/(서류|징구|제출|계약서|확인서|증명서|신고서|서약서|내역서)/.test(x.text)).slice(0,6);else if(it==='omit')c=ss.filter(x=>/(생략|면제|대체|해당없음)/.test(x.text)).slice(0,4);else if(it==='safety')c=ss.filter(x=>/(안전|보건|추락|위험|보호구|체크리스트)/.test(x.text)).slice(0,6);if(!c.length)c=ss.slice(0,5);const lead=it==='docs'?'지침상 관련 서류는 다음과 같이 확인됩니다.':it==='amount'?'지침상 금액 기준은 다음과 같습니다.':it==='omit'?'지침상 생략·면제 기준은 다음과 같습니다.':it==='safety'?'지침상 안전·보건 관련 핵심 사항은 다음과 같습니다.':'지침에서 질문과 가장 관련성이 높은 내용은 다음과 같습니다.';return{text:lead+'\\n'+c.map(x=>'• '+x.text).join('\\n'),refs:hits.slice(0,6)}}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function answer(q0){const q=(q0||document.getElementById('q').value).trim();if(!q)return;const hits=retrieve(q),obj=synth(q,hits),r=document.getElementById('result');if(!hits.length){r.innerHTML='<div class="empty">'+esc(obj.text)+'</div>';return}r.innerHTML=`<div class="answer"><h2>답변</h2><div class="answerText">${esc(obj.text).replace(/\\n/g,'<br>')}</div><div class="warn">※ 이 챗봇은 첨부된 2023.12.27. 개정 지침만 근거로 답합니다. 실제 업무 적용 전 최신 법령·예규·지침 개정 여부를 확인하세요.</div></div><div class="refs">${obj.refs.map(h=>`<div class="ref"><div class="loc">${esc(h.loc)}</div><div class="snippet">${esc(nearby(h).map(x=>x.text).join(' '))}</div><div class="score">관련도 ${h.score}</div></div>`).join('')}</div>`}
const qs=['1인 수의계약 얼마까지 가능해?','계약서 안 써도 되는 금액이 얼마야?','물품 계약할 때 필요한 서류 알려줘','동일업체 수의계약 몇 번까지 가능해?','공사할 때 안전보건 체크리스트 필요해?','학교 물품 선정위원회는 몇 명으로 구성해?'];document.getElementById('chips').innerHTML=qs.map(q=>`<button class="chip">${esc(q)}</button>`).join('');document.querySelectorAll('.chip').forEach((b,i)=>b.onclick=()=>{document.getElementById('q').value=qs[i];answer(qs[i])});document.getElementById('go').onclick=()=>answer();document.getElementById('q').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();answer()}});decode().then(db=>{DB=db;IDX=build(db);document.getElementById('status').textContent=`JSON 내장 완료 · ${IDX.length.toLocaleString()}개 문장 인덱싱`}).catch(e=>document.getElementById('status').textContent='문서 로딩 실패: '+e.message);
</script></body></html>'''
p.write_text(html.replace('__PAYLOAD__',payload),encoding='utf-8')
print('rebuilt index.html',p.stat().st_size)
